name: Release
on:
  push:
    tags:
      - "*-d2iq.*"

# Because variables are not exported, they are not visible by child processes, e.g. make
env:
  registry: ghcr.io/mesosphere
  registry_username: ${{ github.actor }}
  registry_password: ${{ secrets.GITHUB_TOKEN }}
  version: ${{ github.ref_name }}

jobs:
  release:
    name: Release
    runs-on:
      - ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.registry }}
          username: ${{ env.registry_username }}
          password: ${{ env.registry_password }}
      - name: Build and push container image
        # Note: The Makefile targets will read the version from $(pwd)/release/version
        run: |
          echo ${{ env.version }} > release/version
          make csi \
            REGISTRY=${{ env.registry }}
